### ISSUE TITLE
Enable Travis CI builds

### ISSUE THREAD

**Issue by RyanGlScott** [AndrasKovacs/singleton-nats#5]
I pushed some basic Travis CI setup in https://github.com/AndrasKovacs/singleton-nats/commit/577e48bf8f87c5f9d2b4b39c7be41def6d910c97, but Travis itself [won't build](https://travis-ci.org/AndrasKovacs/singleton-nats/builds) unless it's specifically enabled, which I don't have the power to do.

@AndrasKovacs, might you be able to do this?

**Comment by AndrasKovacs** [comment]
I activated the Travis. It'll build on next commit, I believe.

**Comment by RyanGlScott** [comment]
Awesome, thanks!
